package com.example.selenium;// Generated by Selenium IDE

import org.testng.annotations.Test;



public class TestloginTest extends BaseTest {

  @Test
  public void testlogin() {
    steps.login("tomsmith", "SuperSecretPassword!")
           .checkSecureArea("Secure Area")
            .logOut();
  }
}
